spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/productos/**
        - id: carritos-service
          uri: lb://carritos-service
          predicates:
            - Path=/carritos/**
        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/ventas/**
server:
  port: 443