productos:
  property: Productos Profile Default
server:
  port: 8002
spring:
  application:
    name: productos-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/productos-service?serverTimezone=UTC
    username: root
    password: ""
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka